[package]
name = "cellvec"
version = "0.1.0"
edition = "2021"

[dependencies]
array-init = "2.0"

[dev-dependencies]
qcell = "0.5"

[[example]]
name = "game_rc"

[[example]]
name = "game_rc_pool"

[[example]]
name = "game_tcell"
