[package]
name = "cellvec"
version = "0.1.0"
edition = "2021"

[dependencies]
array-init = "2.0.0"
qcell = "0.5.0"

[[example]]
name = "game"

[[example]]
name = "game_rc"

[[example]]
name = "game_rc_pool"

[[example]]
name = "game_tcell"
